// <auto-generated />
namespace gasDiesel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addsubjectfieldsformetrics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsubjectfieldsformetrics));
        
        string IMigrationMetadata.Id
        {
            get { return "202104190734473_Add subject fields for metrics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
